#!/usr/bin/perl -w
###############################################################################
#	Copyright 2012 BITart Gerd Knops,  All rights reserved.
#
#	Project	: ApLo
#	File	: logParser
#	Author	: Gerd Knops gerti@BITart.com
#
###############################################################################
#
#	History:
#	120103 Creation of file
#
###############################################################################
#
#	Description:
#	Parses system log, prepares for ApLo
#
###############################################################################
#
# DISCLAIMER
#
# BITart and Gerd Knops make no warranties, representations or commitments
# with regard to the contents of this software. BITart and Gerd Knops
# specifically disclaim any and all warranties, whether express, implied or
# statutory, including, but not limited to, any warranty of merchantability
# or fitness for a particular purpose, and non-infringement. Under no
# circumstances will BITart or Gerd Knops be liable for loss of data,
# special, incidental or consequential damages out of the use of this
# software, even if those damages were foreseeable, or BITart or Gerd Knops
# was informed of their potential.
#
###############################################################################
# Configuration
###############################################################################
	
	use strict;
    use feature "switch";
	
	$|=1;

###############################################################################
# Main
###############################################################################
	
	if(scalar(@ARGV)==1)
	{
		given($ARGV[0])
		{
			when ('-js') { printJavascript(); exit(0); }
			when ('-css') { printCSS(); exit(0); }
		}
	}
	
	our	$AppID=$ENV{APLO_WINDOW_NAME};
	
	# open(IN,"syslog -w all -k Sender Seq $AppID|")
	# open(IN,"syslog -w 10 -k Sender Seq $AppID|")
	open(IN,"syslog -w 0 -k Sender Seq $AppID|")
		or die("Can't open 'syslog -w all -k Sender Seq $AppID|' for read: $!\n");
	while(<IN>)
	{
		chomp();
		
		# Remove syslog prefix
		# Dec 29 15:30:19 atlantis [0x0-0xc74c74].com.hhshoppers.Forge[91260] <Notice>:
		s/^\S+\s+\d+\s+\d+\:\d+\:\d+\s+\S+\s+\S+\s*<([^>]+)>\:\s?//;
		
		my $syslogSeverity=$1;
		my $extraClass='';
		
		&htmlEscape;
		
		if(s/^(([^:]+):(\d+):)//)
		{
			my $path=$2;
			my $line=$3;
			
			my $file=$path;
			$file=~s/.*\///;
			
			$extraClass=" appOutput$1" if(/^\s*(WARNING|ERROR|ASSERTION)\:/);
			
			$path=percentEscape($path);
			
			$_=qq{<a href="http://localhost:8091/?message=$path:$line">$file:$line:</a>$_};
		}
		
		print qq{<span class="appOutput$extraClass">$_</span><br />\n};
	}
	close(IN);
	

###############################################################################
# Subroutines
###############################################################################
sub htmlEscape {
	
	s/</&lt;/g;
	s/>/&gt;/g;
	s/\n/<br \/>/g;
}
sub percentEscape {
	
	my $s=shift;
	
	# $s=~s/([^a-zA-Z0-9_\-.\/])/uc sprintf("%%%02x",ord($1))/eg;
	$s=~s/(\s|[]\!\*\'\(\)\;\:\@\&\=\+\$\,\?\#\[\]])/uc sprintf("%%%02x",ord($1))/eg;
	
	$s;
}

###############################################################################
# Javascript & CSS
###############################################################################
sub printJavascript {
	
	print <<'JAVASCRIPT';
JAVASCRIPT
}
sub printCSS {
	
	print <<'CSS';
	.appOutput {
		font: 12px "Monaco", "Courier New", monospace;
		white-space: pre-wrap;
	}
	.appOutputWARNING {
		color: GoldenRod;
	}
	.appOutputERROR {
		color: FireBrick;
	}
	.appOutputASSERTION {
		color: white;
		font-weight: bold;
		background: FireBrick ;
	}	
CSS
};

1;
############################################################################EOF